ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

FileName:
  Enabled: false

IfUnlessModifier:
  Enabled: false

MethodLength:
  Enabled: false

ModuleFunction:
  Enabled: false

OneLineConditional:
  Enabled: false

ParameterLists:
  Enabled: false

Proc:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

VariableInterpolation:
  Enabled: false

TrailingComma:
  Enabled: false

WhileUntilModifier:
  Enabled: false

PredicateName:
  NamePrefixBlacklist:
    - is_

StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

DotPosition:
  EnforcedStyle: leading

SpaceBeforeBlockBraces:
  EnforcedStyle: space

SpaceInsideBlockBraces:
  EnforcedStyle: no_space

DoubleNegation:
  Enabled: false

SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

LineLength:
  Max: 130

RegexpLiteral:
  MaxSlashes: 0

SpaceInsideHashLiteralBraces:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'
