name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests with Ruby ${{ matrix.ruby }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7.x", "2.6.x", "2.5.x"]
        gemfile:
          - Gemfile
          - gemfiles/rails5.gemfile
          - gemfiles/rails6.gemfile

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles('**/${{matrix.gemfile}}') }}
          restore-keys: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles('**/${{matrix.gemfile}}') }}

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gem dependencies
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{matrix.gemfile}}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{matrix.gemfile}}
        run: |
          bundle exec rake
